### ISSUE TITLE
安装完omcproxy插件，openwrt固件立即崩溃

### ISSUE THREAD

**Issue by dodojie** [riverscn/luci-app-omcproxy#2]
我使用的是lean的openwrt固件，固件版本是R9.12.31 ，内核版本是4.19.93

当我安装完您的这个插件，固件立即就崩溃了，web页面进不去（抱歉，当时忘了截图报错信息了），貌似是提示global“view”什么玩意来着。。。。网络也断了。。后来，我通过ssh用命令终端把omcproxy相关软件卸载了之后，才好了

**Comment by dodojie** [comment]
讲真，您这个插件确实不错，可以web页面配置，简单多了。。可惜，不知道哪里的bug，没使用成功

**Comment by riverscn** [comment]
lean固件不兼容新的官方固件UI开发方法，所以可能出问题
我是在官方openwrt里用的

**Comment by riverscn** [comment]
现在这个插件已经合并到了官方库里
https://github.com/openwrt/luci/tree/master/applications/luci-app-omcproxy
所以如果用官方固件的话，能够直接搜索安装

**Comment by mumuou** [comment]
同样悲剧，用大雕源的只能看着，兼容不了，目前大部分个人fork的luci都还是基于18.06的。

**Comment by SingTsang** [comment]
/usr/lib/lua/luci/controller/omcproxy.lua:11: attempt to call global 'view' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/omcproxy.lua:11: in function 't'
	/usr/lib/lua/luci/dispatcher.lua:465: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:188: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

安装luci-app-omcproxy_0.1.0-1_all.ipk就出错

**Comment by riverscn** [comment]
@SingTsang 你用的什么openwrt版本？

**Comment by SingTsang** [comment]
> @SingTsang 你用的什么openwrt版本？

OpenWrt R20.3.11

**Comment by SingTsang** [comment]
> @SingTsang 你用的什么openwrt版本？

OpenWrt R20.3.11

我尝试过降级版本，还是这个错误。

**Comment by riverscn** [comment]
@SingTsang 官方的openwrt还是lean的版本？

**Comment by SingTsang** [comment]
@riverscn lean的版本

**Comment by SingTsang** [comment]
@riverscn IPTV助手就没有问题，就这个包有兼容问题。

**Comment by riverscn** [comment]
@SingTsang 前面讲过了，lean的版本这个app是不支持的。只支持官方版。因为lean不兼容新版的luci。

**Comment by SingTsang** [comment]
@riverscn 没办法啊，我也想用官方版的，但是不兼容我这个路由器，唉

**Comment by SingTsang** [comment]
@riverscn ASUS RT-ACRH17官方没有出固件

**Comment by SingTsang** [comment]
@riverscn 老大如果有时间做个lean版本吧

**Comment by lynml** [comment]
大佬昨天（4月3日）19.07还可以用你这个，效果非常好（天津联通光猫iptv、internet和你教程中的一样）。但是今天我在新机器上设置，已经用不了了。不知为什么。我用官方那个omcproxy没有用呢，用你这个装上1秒直接rtp就可以播放了。我看错误原因 是不是下载地址无效了。。。我去搜了下/19.07-SNAPSHOT/这个版本已经没了。
**Installing luci-app-omcproxy (0.1.0-1) to root...
Installing luci-compat (git-20.094.46635-de52000-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07-SNAPSHOT/packages/x86_64/luci/luci-compat_git-20.094.46635-de52000-1_all.ipk
Collected errors:**

我用的是19.07的官方固件。该怎么弄呢。我下载了你的omcproxy文件放在了tmp文件夹中，可是每次执行opkg install /tmp/下载的文件.ipk 都会显示上面的代码。昨天还好好的。。

**Comment by riverscn** [comment]
@lynml 你先 opk update 再安装试试？

**Comment by lynml** [comment]
> @lynml 你先 opk update 再安装试试？

       每次装软件我都opkg。。找了很久教程。就大佬这个适合北方的联通的软路由。给大佬点个赞。我之前备份了一份虚拟机。现在恢复了，又可以用了。但是新装不知为什么不行了。
       还有就是机顶盒按教程设置完后，还是用不了，和教程设置的一模一样，有线无线mac都试了。开机就提示epg获取失败，进不去首页。

**Comment by lynml** [comment]
> @lynml 你先 opk update 再安装试试？

大佬我觉得你应该把这个帖子多宣传宣传，软路由iptv 联通的教程我找了半天就你这个，关键还好用。

**Comment by wenpo1975** [comment]
大佬，同样的问题，如何解决？

lean SNAPSHOT 安装luci-app-omcproxy后无 “组播代理”界面，卸载后出现
/usr/lib/lua/luci/controller/omcproxy.lua:11: attempt to call global 'view' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/omcproxy.lua:11: in function 'v'
	/usr/lib/lua/luci/dispatcher.lua:572: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:238: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

无法进入web界面，求救，不想重装。
