### ISSUE TITLE
安装后无luci显示

### ISSUE THREAD

**Issue by nmvbxcz** [riverscn/luci-app-omcproxy#3]
coolsnowwolf/lede  编译的最新的固件，从软件包里面直接安装的luci-app-omcproxy和luci-i18n-app-omcproxy-zh-cn，但是在服务里面找不到组播代理项目，不知道为什么
如果从命令行安装omcproxy会报错
Collected errors:
 * check_data_file_clashes: Package libubox20191228 wants to install file /lib/libubox.so
	But that file is already provided by package  * libubox20170601
 * opkg_install_cmd: Cannot install package omcproxy.

**Comment by riverscn** [comment]
![截屏2020-04-05 下午4 38 46](https://user-images.githubusercontent.com/555062/78470443-3817c580-775c-11ea-80d2-be0c7e42a9bb.png)
