### ISSUE TITLE
Openwrt 19.07版本编译此包后打开主页报错

### ISSUE THREAD

**Issue by greatt1n** [riverscn/luci-app-omcproxy#5]
固件信息

主机名	OpenWrt
主机型号	XiaoYu XY-C5
架构	MediaTek MT7621 ver:1 eco:3
固件版本	OpenWrt 19.07-SNAPSHOT / LuCI 18.06 Lienol (git-eb8d90f)
内核版本	4.14.180

加入luci-app-omcproxy编译后主页报错，信息如下
/usr/lib/lua/luci/controller/omcproxy.lua:11: attempt to call global 'view' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/omcproxy.lua:11: in function 'v'
	/usr/lib/lua/luci/dispatcher.lua:621: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:266: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:127: in function </usr/lib/lua/luci/dispatcher.lua:126>

ssh登录路由删除  opkg remove luci-app-omcproxy后登录正常。

**Comment by greatt1n** [comment]
尝试使用官方Luci里的luci-app-omcproxy编译，结果界面不报错了，但是看不到omcproxy配置选项。
能不能维护一下或者用哪一个版本的Openwrt编译能够正常使用？

**Comment by riverscn** [comment]
19.07.2

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: greatt1n <notifications@github.com>
发送时间: Sunday, June 7, 2020 9:06:23 PM
收件人: riverscn/luci-app-omcproxy <luci-app-omcproxy@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [riverscn/luci-app-omcproxy] Openwrt 19.07版本编译此包后打开主页报错 (#5)


尝试使用官方Luci里的luci-app-omcproxy编译，结果界面不报错了，但是看不到omcproxy配置选项。
能不能维护一下或者用哪一个版本的Openwrt编译能够正常使用？

―

**Comment by riverscn** [comment]
增加了18.06的兼容分支，所以本贴关闭。
