### ISSUE TITLE
组播每隔4分钟左右断流

### ISSUE THREAD

**Issue by 13528943945** [riverscn/luci-app-omcproxy#8]
首先感谢作者的插件。另外请教一个问题就是，组播信号播放4分钟左右即中断，需重新手工再次点击播放。请问有解决方法吗？

**Comment by riverscn** [comment]
你打开了igmp snooping了吗

myfirstgit ***@***.***>于2022年3月7日 周一18:39写道：

**Comment by 13528943945** [comment]
光猫里面默认开了snooping，而且还有一个300秒的参数。openwrt里面没开

**Comment by riverscn** [comment]
路由里，交换机里，也要打开

myfirstgit ***@***.***>于2022年3月8日 周二09:29写道：

**Comment by 13528943945** [comment]
傻瓜交换机，没得设置
