### ISSUE TITLE
openwrt安装后无法打开路由web管理界面

### ISSUE THREAD

**Issue by douQiuYu343** [riverscn/luci-app-omcproxy#9]
/usr/lib/lua/luci/controller/omcproxy.lua:11: attempt to call global 'view' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/omcproxy.lua:11: in function 'v'
	/usr/lib/lua/luci/dispatcher.lua:577: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:243: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:126: in function </usr/lib/lua/luci/dispatcher.lua:125>

**Comment by riverscn** [comment]
> /usr/lib/lua/luci/controller/omcproxy.lua:11: attempt to call global 'view' (a nil value) stack traceback: /usr/lib/lua/luci/controller/omcproxy.lua:11: in function 'v' /usr/lib/lua/luci/dispatcher.lua:577: in function 'createtree' /usr/lib/lua/luci/dispatcher.lua:243: in function 'dispatch' /usr/lib/lua/luci/dispatcher.lua:126: in function </usr/lib/lua/luci/dispatcher.lua:125>

https://github.com/riverscn/luci-app-omcproxy/blob/master/README.md

请仔细阅读说明
